### ISSUE TITLE
Multiple colored nodes are not supported

### ISSUE THREAD

**Issue by shivangi1787** [wikipathways/rWikiPathways#1]
Hi all,

How do we color multiple xrefIDs in a single pathway. I am using the R package, "rWikiPathways".
Any suggestions would be appretiated.

Thanks

**Comment by AlexanderPico** [comment]
Hi,

This is a known bug in the WikiPathways webservice. Once it's fixed there, then the R package will work. Until then, there is a not in the man page for this function:

> only single values are supported at this time

**Comment by AlexanderPico** [comment]
@shivangi1787 Good news. This is now fixed in the R package.
