### ISSUE TITLE
commit 2ba575e338706e1c6ffa7707e7d10ff78839e71a undid earlier fixes

### ISSUE THREAD

**Issue by egonw** [wikipathways/rWikiPathways#14]
Alex, can you plz have a look at commit 2ba575e338706e1c6ffa7707e7d10ff78839e71a ? It undid the replacement of RJSONIO with rjson :(

Was that by accident?

**Comment by egonw** [comment]
Actually, not only that commit.

**Comment by AlexanderPico** [comment]
Not sure what prompted those changes that I committed. I recall making them in response to devtool:check errors, so something must have been missing... maybe? In any case, I've changed them back and checks pass without errors or warnings.

Sorry about that!
