### ISSUE TITLE
GMT parsing is missing

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/rWikiPathways#16]
We shouldn't rely on clusterProfiler for read.gmt. It's a basic function and our version could include the % parsing that is unique to our files. 

Suggestion: Add readPathwayGMT()

**Comment by GuangchuangYu** [comment]
the source code is just a copy-paste from `clusterProfiler::read.gmt()`. I think proper acknowledgement is needed.

**Comment by AlexanderPico** [comment]
Sure, happy to. I'll add an acknowledgement to the functions man description.

**Comment by GuangchuangYu** [comment]
thanks.
