### ISSUE TITLE
proper acknowledgement

### ISSUE THREAD

**Issue by GuangchuangYu** [wikipathways/rWikiPathways#17]
some of your <https://github.com/wikipathways/rWikiPathways/blob/master/vignettes/Pathway-Analysis.Rmd> vignette was adopted from `clusterProfiler`. You need to acknowledge it.

**Comment by AlexanderPico** [comment]
Hi @GuangchuangYu, I don't think we've formally met yet. I actually wrote that part of the clusterProfiler vignette. I wrote both at the same time :) 

https://github.com/YuLab-SMU/clusterProfiler/pull/159

Both vignettes do acknowlege each other by way of library use and source mentions. I'm happy to include additional cross-references if you have specific suggestions.

**Comment by GuangchuangYu** [comment]
oops, I totally forget it. That's my fault.
