### ISSUE TITLE
Link to BridgeDb datasource list in documentation is wrong

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/rWikiPathways#19]
It's cutoff in the PDF: 
![image](https://user-images.githubusercontent.com/2158343/101018888-6f00de00-356c-11eb-845e-7476d3c2f0d7.png)

And wrong in the HTML of the vignette:
https://www.bioconductor.org/packages/release/bioc/vignettes/rWikiPathways/inst/doc/Overview.html
> https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt

.txt was changed to .tsv I think. 

Is it enough if I change it in the Rmd file or do I also need to change it in the HTML page?

**Comment by AlexanderPico** [comment]
Thanks for catching this.

We only provide the Rmds in our codebase. Bioconductor auto-generates the HTML based on the Rmds provided.

**Comment by egonw** [comment]
Also related: https://github.com/wikipathways/rWikiPathways/pull/21 and https://github.com/wikipathways/rWikiPathways/pull/20
