### ISSUE TITLE
downloadPathwayArchive() not working

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/rwikipathways#24]
From Tina:

rWikiPathways::downloadPathwayArchive() is currently not working. I get an error:

Error in function (type, msg, asError = TRUE)  : SSL certificate problem: certificate has expired

**Comment by AlexanderPico** [comment]
Works for me. Tests pass and both checks pass.

**Comment by qqwxp** [comment]
I got the same error when I run
wp.hs.gmt <- downloadPathwayArchive(date="current", organism="Homo sapiens", format = "gmt")

**Comment by AlexanderPico** [comment]
Still works fine for me. Not sure how to reproduce this error.  @mkutmon Do you still see this error?
