### ISSUE TITLE
igraph compatible?

### ISSUE THREAD

**Issue by emantzo** [wikipathways/rWikiPathways#25]
Hi, thank you for your work!
I was wondering if the data could be extracted in a format compatible with igraph.
Hope my question it's not too naive.
Thank you!

**Comment by AlexanderPico** [comment]
Great question. The answer is yes, but I'm not sure what it acutally would look like. Here's how you'd do it:

1. Using the RCy3 package you could load a WikiPathways diagram into Cytoscape. See https://new.wikipathways.org/rWikiPathways/articles/rWikiPathways-and-RCy3.html#working-together.
2. Then the RCy3 package also provides `createIgraphFromNetwork()` which will load the Cytoscape model as an igraph network. 

Caution. The modeling of pathway information in GPML (WikiPathways) and Cytoscape is rich with information that igraph simply doesn't support, so information will certainly be lost and there may be weird items in igraph that don't make sense. So, I'm not recommending this workflow in general, but perhaps you can make it work for a few pathways for your particular needs.

Another tip: I'd try and alternative Step 1 (if you don't like what you get), where you replace `import-as-pathway` with `import-as-network`. That route attempts to simplify the pathway model in Cytoscape, making the conversion to igraph a bit more straightforward.
