### ISSUE TITLE
Error in function (type, msg, asError = TRUE)  :    SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by duanxiaoqian** [wikipathways/rwikipathways#26]

**Comment by lbuschma** [comment]
Hopefully someone can help here. I got the same Error, when using rWikiPathways in Rstudio today. I am using the [RVA](https://github.com/THERMOSTATS/RVA) package to visualize my data and it uses rWikiPathways for one part of it. I tested KEGG and REACTOME pathway analysis from the same package. Both work fine, just rWikiPathways gives me this error: "SSL certificate problem: certificate has expired"

**Comment by AlexanderPico** [comment]
@duanxiaoqian I can't reproduce this error. I tried a few functions in rWikiPathways and they work fine. Which function returns the SSL error?

@lbuschma I installed RVA and ran through the tutorial. I did not see this error. What steps are you performing to get the SSL error?

**Comment by lbuschma** [comment]
Thanks for the quick answer.
I basically adjusted the code from the tutorial to my needs and just used my RNAseq Dataset instead of the Dataset provided by the tutorial. 
This is the code I used, whereas RNAseqENSEMBLordered is a Data Set with the EnsemblIDs as Rownames and the logFC and adj.p-Value (the only relevant columns, in my case I ordered it after the Expression (Column named: t). So only the input changed, rest is default settings of the Tool.
```

#Pathway Analysis Plots
RNAseqENSEMBLordered <- RNAseqEnsembl_names_HAP1[order(RNAseq_EnsemblIDs_HAP1$t, decreasing = TRUE),]
pathway.result <- plot_pathway(data = RNAseqENSEMBLordered,
                               pathway.db = "rWikiPathways",
                               gene.id.type = "ENSEMBL",
                               FC.cutoff = 1.2,
                               FDR.cutoff = 0.05,
                               Fisher.cutoff = 0.1,
                               Fisher.up.cutoff = 0.1,
                               Fisher.down.cutoff = 0.1)
pathway.result 
```

Afterwards I get this error:
```
 Running plot pathway. Acceptable data types are list() & data.frame() 




 Current program setting only accepts rownames as ENSEMBL, use parameter `gene.id.type` to adjust if needed. 



 Currently using the rWikiPathways database for enrichment 


Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: certificate has expired
```

Therefore I tested the other pathway analysis options the tool provides, as example KEGG (same dataset):
```
pathway.KEGG <- plot_pathway(data = RNAseqENSEMBLordered,
                               pathway.db = "KEGG",
                               gene.id.type = "ENSEMBL",
                               FC.cutoff = 1.2,
                               FDR.cutoff = 0.05,
                               Fisher.cutoff = 0.1,
                               Fisher.up.cutoff = 0.1,
                               Fisher.down.cutoff = 0.1,)
pathway.KEGG

 Running plot pathway. Acceptable data types are list() & data.frame() 




 Current program setting only accepts rownames as ENSEMBL, use parameter `gene.id.type` to adjust if needed. 



 Currently using the KEGG database for enrichment 


More pathways in directional data than non directional data 
hence using pathways exsting in directinal dataset

 Plot file name not specified, a plot in ggplot object will be returned! 
```

This works fine, I get a table and a plot with enriched KEGG pathways. That's the reason I was puzzled by the outcome, because I did the same analysis with another dataset 6 months ago and it worked fine, rWikiPathways and KEGG.

**Comment by AlexanderPico** [comment]
Again, it works for me. But, I suspect your system is complaining about the legacy `http` url in the rWikiPathways package, so I've updated that and you can install a dev version from GitHub by... 

```
install.packages("devtools")
library(devtools)
install_github('wikipathways/rWikiPathways', build_vignettes=TRUE)
library(rWikiPathways)
```

However, even if this fixes the SSL error you are seeing, it appears as though RVA doesn't know how to parse the WikiPathways gmt format, so you will like just run into a subsequent error about reading the "Description" field which is delimlited by `%` in our gmts.  

So, I think changes in the RVA code are needed to actually work with rWikiPathways. Sorry :(
