### ISSUE TITLE
404 error when trying to use clusterProfiler::enrichWP

### ISSUE THREAD

**Issue by d-henness** [wikipathways/rWikiPathways#35]
I'm following along with this https://bioconductor.org/packages/devel/bioc/vignettes/rWikiPathways/inst/doc/Pathway-Analysis.html#1_Installation and everything works until this point

```
ewp.up <- clusterProfiler::enrichWP(
    up.genes.entrez[[2]],
    universe = bkgd.genes.entrez[[2]],
    organism = "Homo sapiens",
    pAdjustMethod = "fdr",
    pvalueCutoff = 0.1, #p.adjust cutoff; relaxed for demo purposes
)
```

which gives this error
```
Error in file(con, "r") :
  cannot open the connection to 'https://wikipathways-data.wmcloud.org/current/gmt/'
Calls: <Anonymous> ... eval -> <Anonymous> -> do.call -> <Anonymous> -> file
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://wikipathways-data.wmcloud.org/current/gmt/': HTTP status was '404 Not Found'
Execution halted
```

everything was working fine last week so I'm not really sure what the problem could be. Going to the link in my browser shows there is a website at https://wikipathways-data.wmcloud.org/ but it's pretty blank. Is it just down for maintenance or something?

**Comment by AlexanderPico** [comment]
Indeed, that URL is outdated and should have never been in the clusterProfiler code. We use this forward-compatible domain instead: data.wikipathwayw.org. I submitted the patch to fix this 8 months ago and it is in the latest code: https://github.com/YuLab-SMU/clusterProfiler/commits/devel/R/wikiPathways.R. 

Perhaps you are using an older version of clusterProfiler? Please try upgrading the package to the latest version and let us know if you still have the issue.

It may have also just been a temporary issues. In any case, we could not reproduce it with our installation.

**Comment by AlexanderPico** [comment]
The Bioconductor site now allows one to browse the code for specific releases, so I could confirm that the wrong (wmcloud) URL is present in the prior two releases 3_17 and 3_18, but has been restored to the correct URL in the latest 3_19 release of clusterProfiler. Thus, an update should fix this issue.

https://code.bioconductor.org/browse/clusterProfiler/tree/RELEASE_3_19/R/
