### ISSUE TITLE
findPathwaysByText should return data.frame rather than list?

### ISSUE THREAD

**Issue by kozo2** [wikipathways/rWikiPathways#7]
(This is not bug report. This is feature request.)

I created an automation Rmd for rWikipathways.
https://nrnb.org/gsod2019_kozo_nishida/html_documents/Rmd/wikipathways-app.html

I thought findPathwaysByText should return data.frame rather than list.
How do you think about this?

**Comment by AlexanderPico** [comment]
Nice idea! Will do this for Text, LIterature and Xref based queries
