### ISSUE TITLE
migrate away from RJSONIO to rjson

### ISSUE THREAD

**Issue by egonw** [wikipathways/rWikiPathways#8]
The reason is that the first uses a header file from json.org which has a MIT-no-evil license and therefore is only in Debian non-free. After we moved, our R package can go into Debian. cc @tillea

**Comment by egonw** [comment]
@AlexanderPico, I have patches to address this in this PR: https://github.com/egonw/rWikiPathways/pull/11

If you are happy with the patches, I will prepare a proper pull request. After that, I also will want to backport this to the current stable release, as I think both can be considered bug fixes.

**Comment by AlexanderPico** [comment]
Yes, please do. Thanks!
