### ISSUE TITLE
`getColoredPathway` should recognize if the remote API method is offline

### ISSUE THREAD

**Issue by egonw** [wikipathways/rWikiPathways#9]
@AlexanderPico, the alternative is, of course, the remove the method altogether.

**Comment by egonw** [comment]
@AlexanderPico, I have patches to address this in this PR: https://github.com/egonw/rWikiPathways/pull/11

If you are happy with the patches, I will prepare a proper pull request. After that, I also will want to backport this to the current stable release, as I think both can be considered bug fixes.

**Comment by egonw** [comment]
(I found this issue when working on https://github.com/wikipathways/rWikiPathways/issues/8)

**Comment by AlexanderPico** [comment]
Yes, if you can provide a patch against the master, then I can handle pushing it to dev and current release branches here and upstream (i.e., bioconductor).

**Comment by AlexanderPico** [comment]
deprecated in 1.8.0 release
